Feature/header
vnko1/fs67-project16 pull request #6
Opened 2022-11-20 15:11 UTC by EugeneAndroschuk

добавил хедер на все страницы html

2022-11-20 16:28 UTC, vnko1 requested changes
мобильное меню не смотрел

2022-11-20 16:28 UTC, vnko1 commented on src/sass/layout/_header.scss
> +  z-index: 1000;
повторяется код, такие же ширина контейнера и боковые падинги есть у селектора .container, 
на точках перелома тоже повторяются падинги и свойство left имеют одинаковые значения.
Высоту мы задаем только декоративным елементам, а еще не понятно, для чего свойтсво left и translate

2022-11-20 16:28 UTC, vnko1 commented on src/sass/layout/_header.scss
> +.menu-btn {
кнопка залазит на правый падинг
<img width="1440" alt="Знімок екрана 2022-11-20 о 18 14 58" src="https://user-images.githubusercontent.com/102794464/202913186-5af6e535-487a-4de1-9268-e5c742e5561c.png">

2022-11-20 16:28 UTC, vnko1 commented on src/sass/layout/_header.scss
> +.header-btn {
размер кнопки по макету 95х40, а у тебя 101х46

2022-11-20 17:11 UTC, EugeneAndroschuk commented on src/sass/layout/_header.scss
> +  z-index: 1000;
у хедера абсолютное позиционирование, ему нужно отдельно все прописывать, по-другому не получается

2022-11-20 20:08 UTC, EugeneAndroschuk commented on src/sass/layout/_header.scss
> +  z-index: 1000;
запушил коммит - убрал высоту (задал ее паддингами), убрал ширину - она теперь тянется из контейнера, а лефт и транслейт оставляю, т.к. абсолютное позиционирование и нужно отцентрировать хедер по вьюпорту

2022-11-20 20:10 UTC, EugeneAndroschuk commented on src/sass/layout/_header.scss
> +  }
это отдельный div, чтобы ему по всей ширине вьюпорта задать тень, чтобы он соответствовал высоте хедера... по-другому пока не придумал

2022-11-20 20:15 UTC, EugeneAndroschuk commented on src/sass/layout/_header.scss
> +.header-btn {
запушил коммит - подправил размеры кнопок... кнопка которая была у меня сделана - она для десктопа, а для таблетки изменил паддинги... но точный размер все-равно не получается... наверное из-за текста в кнопке

2022-11-21 07:37 UTC, vnko1 approved these changes

2022-11-21 07:37 UTC, merged