feature/sale
vnko1/fs67-project16 pull request #8
Opened 2022-11-20 21:57 UTC by roman-vashchenko

Добавив секцію Sale

2022-11-21 08:47 UTC, vnko1 requested changes

2022-11-21 08:47 UTC, vnko1 commented on src/partials/sale.html
> +        <ul class="sale__list">
По тз картки товарів мають бути реалізовані за допомогою тега <ul> як список посилань, що ведуть на сторінку Take Order Page.

2022-11-21 11:04 UTC, roman-vashchenko commented on src/partials/sale.html
> +        <ul class="sale__list">
виправлено

2022-11-21 11:04 UTC, roman-vashchenko commented on src/partials/sale.html
> +      <a class="sale__btn" href="">View all</a>
виправлено

2022-11-21 12:40 UTC, vnko1 requested changes
1

2022-11-21 12:40 UTC, vnko1 commented on src/sass/layout/_sale.scss
> +  padding-left: 80px;
еще ты тут ставишь падинг 80 px от левой части вьюпорта, но у контейнера тоже есть свой падинг и получается общий падинг заголовка буде 80px + 16px

2022-11-21 12:43 UTC, vnko1 requested changes

2022-11-21 12:43 UTC, vnko1 commented on src/sass/layout/_sale.scss
> +  margin-bottom: 48px;
еще расстояние между секциями, нужно задавать не margin a padding

2022-11-21 12:50 UTC, roman-vashchenko commented on src/sass/layout/_sale.scss
> +  margin-bottom: 48px;
змінено

2022-11-21 12:54 UTC, roman-vashchenko commented on src/sass/layout/_sale.scss
> +  padding-left: 80px;
змінено, в мене тоді виходить на всіх пристроях по 62px, так як на мобільный версії в мене падінги ліворуч праворуч по 18px

2022-11-23 13:01 UTC, vnko1 commented on src/sass/layout/_sale.scss
> +  margin-bottom: 48px;
але зверни увагу, що між  футером та твоєю секцією на різних пристроях різні відстані

<img width="1440" alt="Знімок екрана 2022-11-23 о 15 01 11" src="https://user-images.githubusercontent.com/102794464/203553272-d8b5faa9-4d01-4d50-8496-d712c19180bb.png">

2022-11-23 13:13 UTC, vnko1 requested changes
там по нижньому падінгу на твою секцію подивись коментар, також починаючи щ ширини єкрану 1280 твоя лінія не всю ширину вьюпорту 
<img width="1440" alt="Знімок екрана 2022-11-23 о 15 06 56" src="https://user-images.githubusercontent.com/102794464/203554410-da5ad0b1-68ec-4b15-acad-22f23279cdcf.png">
<img width="1440" alt="Знімок екрана 2022-11-23 о 15 08 29" src="https://user-images.githubusercontent.com/102794464/203555271-79c8a245-938f-47b6-ab25-e74c2c640194.png">
<img width="1440" alt="Знімок екрана 2022-11-23 о 15 10 59" src="https://user-images.githubusercontent.com/102794464/203555280-46d091a8-5b6c-4af0-b0cc-a144401a57fc.png">
і скролу наче нема

2022-11-24 17:58 UTC, roman-vashchenko commented on src/sass/layout/_sale.scss
> +  margin-bottom: 48px;
Виправлено

2022-11-24 19:13 UTC, vnko1 approved these changes

2022-11-24 19:14 UTC, merged